### ISSUE TITLE
Minor Bug: Game over screen 

### ISSUE THREAD

**Issue by pyang3** [joshuaemer/Gold-Team#57]
when you get game over screen there should be a button or action somewhere to get me back to menu so I don't have to restart the game every time I get game over screen.

How to replicate: Lose or use the Leave button.

Image: 
![image](https://user-images.githubusercontent.com/31747401/38060448-c79c146c-32b8-11e8-92da-297ab3ecaf62.png)

**Comment by rdsandid** [comment]
Bug confirmed.  Adding 'major bug' label and will assign to myself.

**Comment by joshuaemer** [comment]
Determined to be a minor bug as actual functionality defined by the user story is not broken.
