### ISSUE TITLE
Player takes damage far away from enemies

### ISSUE THREAD

**Issue by jaredgav** [joshuaemer/Gold-Team#65]
MINOR BUG ... couldn't place a label for some reason.
I seem to be taking damage when I am far away from an enemy. I can see the enemy animation continuing, but I have moved away from the enemy. 

To recreate, egg on the enemies, wait for swing to begin, then back up from the enemy and damage should appear to be taken.

Windows exe release, Alpha Release, run on Windows 10

**Comment by joshuaemer** [comment]
Thank you for reporting this. It has already been reported and resolved. These changes will appear in our new release on Wednesday. I am going to mark this as closed.
