### ISSUE TITLE
[Bug] Boss doesn't move

### ISSUE THREAD

**Issue by jaimeenahn** [joshuaemer/Gold-Team#82]
Boss skeleton is not moving. In detail, he is doing moving motion but he is still there.

![asdacasc](https://user-images.githubusercontent.com/32367255/38900046-0afdfbd0-4268-11e8-8417-d758bd82e032.JPG)

![ascsc](https://user-images.githubusercontent.com/32367255/38900053-0f0f94c2-4268-11e8-913b-4d829aa6c0f8.JPG)

**Comment by joshuaemer** [comment]
Thanks for the report I will look into this.

**Comment by joshuaemer** [comment]
This is an issue with one of the checkpoints being unreachable, should be a quick fix.

**Comment by joshuaemer** [comment]
Also direction in which they follow the points is random so these are hard to catch.
