### ISSUE TITLE
[Bug] Missing User interface in game over screen

### ISSUE THREAD

**Issue by xuanyudo** [joshuaemer/Gold-Team#84]
How to reproduce this:
1. open the game with screen size of 800 * 600.
2. start game.
3. exit game.
4. I can't do anything with the screen below.
![1](https://user-images.githubusercontent.com/14997796/38971005-d178d9de-4366-11e8-9434-e8bbe3a58a5d.JPG)

**Comment by joshuaemer** [comment]
Okay thank you we will look into this.
