### ISSUE TITLE
[Feature Request] More visible spike pit

### ISSUE THREAD

**Issue by yxue5** [joshuaemer/Gold-Team#85]
Hey guys, great work on the project so far! I feel like one thing that would improve the user experience is a more visible spike pit. When I beta-tested the project, it took me a long time to find the spike pit. I feel like making the hole bigger and adding big spikes that you can see before falling into the pit will give players a better understanding of what it is.

**Comment by joshuaemer** [comment]
Thanks for the suggestion.  This will be reflected in the official release.

**Comment by joshuaemer** [comment]
This was added into our last beta release along with the bug fixes. I will close this.
